### ISSUE TITLE
module 'code_ast' has no attribute 'tokenize' Error while trying to run example

### ISSUE THREAD

**Issue by ChethanM555** [cedricrupb/code_diff#1]
I'm just following the readme file and I'm encountering this error when after the output = .... , statement.
![image](https://user-images.githubusercontent.com/38497808/176912143-7d7dd3a4-d25b-40d6-b86f-09bc3fcb57d3.png)

**Comment by cedricrupb** [comment]
Hey Chethan, 

thank you for letting me know. This should be fixed with the current release.
If you have installed code_diff via PIP, you should be able to update to current version now.

**Comment by ChethanM555** [comment]
Hey Cedric,
Thank you for fixing this so soon!
Best,
Chethan M
